# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FD7brhNT2iij5C6Yb4T58bxr0IIiVP0W
"""

print("Hello World")

name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your favorite hobby? ")

print(f"\n🎉 Welcome {name}! 🎉")
print(f"You are {age} years old and you love {hobby}.")

name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your favorite hobby? ")
city = input("Which city do you live in? ")

print("\n🎉 Welcome! 🎉")
print(f"Hello {name}! You are {age} years old, living in {city}, and you enjoy {hobby}.")
print("Nice to meet you! 😊")